# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_schedulerlog_other_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerlog',
            options={'ordering': ['-created_at']},
        ),
    ]
