# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180123_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('school_section', models.TextField()),
                ('cca_group', models.TextField()),
                ('cca_name', models.TextField()),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
    ]
